//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.LineaOrden = new HashSet<LineaOrden>();
        }
    
        public int OrdenID { get; set; }
        public string CorreoElectronicoCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public Nullable<System.DateTime> HoraInicio { get; set; }
        public int EstadoID { get; set; }
    
        public virtual EstadoOrden EstadoOrden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaOrden> LineaOrden { get; set; }
        public virtual Party Party { get; set; }
    }
}
